theme: jekyll-theme-slate
title: "Iceberg"
description: "Uncover the bulk of research."
owner_name: Martin Jucker
owner_url: https://github.com/mjucker
social_media_banners: "true"
twitter: ResearchIceberg
medium: ResearchIceberg
plugins: [jekyll-paginate, jekyll-seo-tag]
